import customtkinter as ctk

def init_theme():
    ctk.set_appearance_mode("System")
    ctk.set_default_color_theme("blue")

# Fonts
FONT_TITLE = ("Tahoma", 18, "bold")
FONT_LABEL = ("Tahoma", 12, "bold")
FONT_TEXT = ("Tahoma", 12)

# Menu Items (Structured as a Dictionary)
MENU_OPTIONS = {
    "Sandwiches": [
        "Chicken Shawarma",
        "Falafel",
        "Beef Kebab",
        "Chicken Kebab",
        "Beef Burger",
        "Chicken Burger",
        "Olivier Sandwich"
    ],
    "Pastry": [
        "Mini Chicken Pizza",
        "Mini Vegetable Pizza",
        "Chicken Puff",
        "Za'atar Bread"
    ],
    "Bread": [
        "Labneh Bread",
        "Labneh with Za'atar",
        "Labneh with Olives",
        "Cheese Bread"
    ],
    "Desserts": [
        "Plain Croissant",
        "Chocolate Croissant",
        "Cheese Croissant",
        "Za'atar Croissant",
        "Date Maamoul",
        "Cupcake",
        "Carrot Cake",
        "Plain Cake",
        "Donuts",
        "Cookies"
    ]
}

# Expenses
# ==========================================
# Expenses Tab Configuration & Fields
# ==========================================

# 1. Document Information Section
DOCUMENT_FIELDS = [
    ("Internal Doc ID:", "Auto-generated by system"),
    ("Invoice Number:", "e.g., INV-1024"),
    ("Receipt / Bill Number:", "Paper receipt ID"),
    ("Order / Check Number:", "Order or Check reference"),
    ("Serial / Batch Number:", "Invoice serial / batch"),
    ("Confirmation / Ref Number:", "Transaction reference ID"),
    ("Invoice Type:", ["Purchase Invoice", "Sales Invoice", "Standard Receipt", "Tax Invoice", "Credit Note", "Debit Note"]),
    ("Status:", ["Draft", "Confirmed", "Voided"]),
    ("Currency:", ["USD ($)", "EUR (€)", "IRR (Rial)", "AED (Dirham)"]),
    ("Language:", ["English", "Persian", "Arabic"])
]

# 2. Seller Information Section
SELLER_FIELDS = [
    ("Business / Company Name:", "e.g., Acme Corp"),
    ("Branch Name / Code:", "e.g., Main Branch / BR01"),
    ("Owner / Manager Name:", "Full Name"),
    ("Commercial Reg (CR) / License:", "Registration Number"),
    ("VAT Number / Tax Registration:", "Tax ID"),
    ("Phone / Mobile:", "Contact number"),
    ("WhatsApp / Email:", "Contact details"),
    ("Website:", "www.example.com"),
    ("Full Address:", "Street, Building, Unit"),
    ("City / Country / Postal Code:", "Location details")
]

# 3. Buyer Information Section
BUYER_FIELDS = [
    ("Buyer / Customer Name:", "e.g., John Doe"),
    ("Customer Code / ID:", "Subscription / National ID"),
    ("Buyer VAT Number:", "Customer Tax ID"),
    ("Buyer Phone Number:", "+1-xxxxxxxxx"),
    ("Buyer Email:", "customer@example.com"),
    ("Customer Type:", ["Individual", "Corporate", "Government"]),
    ("Contact Person / Representative:", "Name of the agent"),
    ("Delivery / Billing Address:", "Destination address")
]

# 4. Payment Information Section
PAYMENT_FIELDS = [
    ("Payment Method:", ["Cash", "POS Terminal", "Bank Transfer", "Cheque", "Credit", "Digital Wallet"]),
    ("Payment Status:", ["Fully Paid", "Unpaid / Outstanding", "Partially Paid"]),
    ("Amount Paid:", "Received Amount"),
    ("Remaining / Balance Due:", "Balance remaining"),
    ("Last 4 Card Digits:", "e.g., 4321"),
    ("Transaction ID / Auth Code:", "Transaction Reference"),
    ("POS Terminal ID (TID):", "Device serial/terminal ID"),
    ("Cashier / Operator Name:", "Active user session")
]

# 5. Tax and Shipping Section
TAX_SHIPPING_FIELDS = [
    ("Official Tax ID of Invoice:", "Electronic Tax Ref Number"),
    ("Tax Configuration:", ["Tax included in price", "Tax added on top"]),
    ("Total VAT Amount:", "Calculated VAT sum"),
    ("Other Taxes / Duties:", "Customs, Excise, or Local fees"),
    ("Shipping Method:", ["Standard Post", "Express Courier", "Freight Cargo", "Self-Pickup"]),
    ("Driver / Carrier Name:", "Shipment partner / driver name"),
    ("Vehicle License Plate:", "Plate details"),
    ("Tracking Number / Waybill:", "Cargo reference code")
]

# 6. Specialized Industry Fields
GAS_STATION_FIELDS = [
    ("Station / Pump Number:", "Station #2 - Pump #4"),
    ("Fuel Type / Nozzle:", ["Regular Octane", "Premium Petrol", "Diesel", "CNG"]),
    ("Fuel Volume (Liters):", "Total liters dispatched"),
    ("Price Per Liter / Odometer:", "Price per unit")
]

RESTAURANT_FIELDS = [
    ("Table Number / Guests count:", "Table #5 - 3 Guests"),
    ("Order Type:", ["Dine-In", "Takeaway", "Home Delivery"]),
    ("Waiter / Order Taker Name:", "Server Name")
]

# 7. Totals Calculations
TOTALS_FIELDS = [
    ("Subtotal (Excl. Tax & Discount):", "0.00"),
    ("Total Discounts:", "0.00"),
    ("Total VAT / Taxes:", "0.00"),
    ("Handling / Service Fees:", "0.00"),
    ("Delivery / Freight Fees:", "0.00"),
    ("Grand Total (Due Amount):", "0.00")
]
